global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "tf-serving-monitor"
 
 
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    metrics_path: /monitoring/prometheus/metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['a443-cc-pipeline-production.up.railway.app']
